    CREATE TABLE ST_CLASS (
        CLASS BIGSERIAL PRIMARY KEY
    );
    CREATE TABLE PARENT(
        P_NO BIGSERIAL PRIMARY KEY
    );

CREATE TABLE STUDENT();

ALTER TABLE STUDENT
ADD COLUMN STUDENT_ID BIGSERIAL PRIMARY KEY,
ADD COLUMN STUDENT_NAME TEXT NOT NULL,
ADD COLUMN STUDENT_AGE INTEGER  NOT NULL,
ADD COLUMN PARENT_NAME TEXT,
ADD COLUMN  PARENT_PHONE_NUMBER INTEGER ,
ADD COLUMN STUDENT_ROLL_NO INTEGER  DEFAULT 0,
ADD COLUMN DOB DATE DEFAULT ('2000-1-1'),
ADD COLUMN STUDENT_CLASS INTEGER;



-- DROP TABLE STUDENT;
-- DROP TABLE ST_CLASS;
-- DROP TABLE PARENT;


